# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b999bdcb31d9e89cdab2fd04aabc4427e8a81de9a018324d6fb49b76216581090e6b0dec6f7023590d56c4cd246212b40baa3a8270ff1145ba1ce03ee5616f01

test:
  secret_key_base: eaf6e9c3e576502e95d7d55a36754c3c6a95e26e5b6a47191b198efda3e2a622adb7376c1ffd474e14ee284d28c9f42380bd9aca19a011273e0164265d8ca06d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
